import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SmoothScrollProvider } from "@/components/providers/SmoothScrollProvider";
import { FloatingDock } from "@/components/navigation/FloatingDock";
import { ModeToggle } from "@/components/ui/ModeToggle";
import { FocusManager } from "@/components/providers/FocusManager";
import { Footer } from "@/components/layout/Footer";
import { GoogleAnalytics } from "@/components/analytics/GoogleAnalytics";
import { ScrollProgress } from "@/components/effects/ScrollProgress";
import { EdgeSparkle } from "@/components/effects/EdgeSparkle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#02040A",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5, // Allow zoom for accessibility
  userScalable: true,
  viewportFit: "cover", // Safe area support for notched devices
};

export const metadata: Metadata = {
  metadataBase: new URL("https://alstonanalytics.com"),
  title: {
    default: "Alston Analytics | Data is organic",
    template: "%s | Alston Analytics",
  },
  description: "Transform raw complexity into executive clarity. Strategic consulting, Power BI engineering, and sovereign thinking.",
  keywords: ["analytics", "consulting", "power bi", "data visualization", "business intelligence"],
  authors: [{ name: "Alston Analytics" }],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  manifest: "/manifest.webmanifest",
  openGraph: {
    title: "Alston Analytics",
    description: "Data clarity. Executive decisions.",
    type: "website",
    locale: "en_US",
    siteName: "Alston Analytics",
    url: "https://alstonanalytics.com",
    // Images are automatically generated by opengraph-image.tsx
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    apple: '/favicon.svg',
    shortcut: '/favicon.ico',
  },
  twitter: {
    card: "summary_large_image",
    title: "Alston Analytics",
    description: "Data clarity. Executive decisions.",
    creator: "@AlstonAnalytics",
    // Images are automatically generated by twitter-image.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="lenis" style={{ backgroundColor: '#02040A' }}>
      <head>
        {/* Prevent white flash on initial load */}
        <style dangerouslySetInnerHTML={{ __html: `html,body{background:#02040A}` }} />

        {/* Preconnect to Google Fonts for faster loading */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Alston Analytics",
              url: "https://alstonanalytics.com",
              logo: "https://alstonanalytics.com/favicon.svg",
              sameAs: ["https://twitter.com/AlstonAnalytics"],
              description:
                "Transform raw complexity into executive clarity. Strategic consulting, Power BI engineering, and sovereign thinking.",
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleAnalytics />
        <a href="#main-content" className="skip-to-content">
          Skip to main content
        </a>
        <SmoothScrollProvider>
          <EdgeSparkle />
          <ScrollProgress />
          <FocusManager />
          <ModeToggle />
          <main id="main-content" tabIndex={-1}>
            {children}
          </main>
          <Footer />
          <FloatingDock />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
